### ISSUE TITLE
[ENHANCEMENT] Customizing content of Toast action

### ISSUE THREAD

**Issue by NdubuisiJr** [Blogrammer/WPF-Toast#10]
Hi @Blogrammer 

I think the content of the `ToastAction` control should come from the user's end. I don't think it is very useful right now because there's no way for the user to change the contents in it.

**Comment by bloggrammer** [comment]
Great point. We could just have sample content for demo purposes.

**Comment by NdubuisiJr** [comment]
Exactly...

I have implemented it already. I moved the contents in the `ToastAction.xaml` to a different `xaml` file in the demo app and simply set the content property of the toast action to it.

**Comment by bloggrammer** [comment]
Aha! Just seeing this after I had pushed the implementation. Maybe you can review my implementation to see if there is room for improvement.

Because the toast action has a fading time interval of 15 secs, I exposed the `CANCEL` event action via an interface so that the toast action control can close immediately after the `CANCEL` button is clicked from the toast content.

**Comment by bloggrammer** [comment]
Maybe, for future fixes and updates, you can assign yourself an issue so one gets to know that you're working on it already.

**Comment by NdubuisiJr** [comment]
I don't have the privilege to assign issues to myself.

**Comment by NdubuisiJr** [comment]
Let me look at your implementation

**Comment by bloggrammer** [comment]
Indicate it in the comment. I'll assign you some privileges soon.

**Comment by NdubuisiJr** [comment]
@Blogrammer the custom view you created is still within the library, I don't think that is accurate. 
The content of the ToastAction should be created outside the library and it should be easily set as soon below:

```
        new ToastAction()
            {
                Title = "Notification: This is Toast Action",
                NotificationMessage = "I am toast action",
                Position = _positions != null ? _positions.Value : Positions.Central,
                PositionReference = _positionReference != null ? _positionReference.Value : PositionReference.Owner,
                Content = new ToastActionContent(), // here
                Owner = this
            };
```
The interface is not necessary, we can simply pass the `CloseAction` to the `Content` object via the `Tag` property, as shown here:

```
            // Inject close action in tag of external contentcontrol. This happens on ToastBase Loaded
            var contentControl = Content as FrameworkElement;
            contentControl.Tag = new Action(CloseAction);
```

This two additions solves the problem.

**Comment by bloggrammer** [comment]
The custom view within the library serves as a sample (Maybe I should move it to the demo project). As you can see below it's been set outside the library in the demo project.

` new ToastAction(new SampleContentOne(), _fadeTimeOut)
            {
                Title = "Notification: This is Toast Action",
                NotificationMessage = "I am toast action",
                Position = _positions != null ? _positions.Value : Positions.Central,
                PositionReference = _positionReference != null ? _positionReference.Value : PositionReference.Owner,
                Owner = this
            };`

**Comment by bloggrammer** [comment]
If you have pulled my work, check the MainWindow.xaml.cs file where I set the custom content though created within the library. I'll take it away from the library.
