### ISSUE TITLE
[FEATURE REQUEST] Add support for custom color

### ISSUE THREAD

**Issue by taha-ghadirian** [Blogrammer/WPF-Toast#7]
Hello, Can you add support for custom colors in your package?

**Comment by bloggrammer** [comment]
The color would have to be specified using hexadecimal color code that way we can support as many colors as possible since we'll have to use a color converter to convert the hexadecimal.

What do you think @taha-ghadirian ?

**Comment by NdubuisiJr** [comment]
Hi @taha-ghadirian and @Blogrammer 

I'm looking at this already. You can assign it to me.

**Comment by NdubuisiJr** [comment]
I think we can close this issue now
